ctp-mocha-mauve: &ctp-mocha-mauve "#cba6f7"

general:
  startup_commands: [ ]
  shutdown_commands: [ ]
  config_reload_commands: [ ]

  toggle_workspace_on_refocus: true
  focus_follows_cursor: false

  cursor_jump:
    enabled: false
    trigger: "window_focus"

  hide_method: "cloak"
  show_all_in_taskbar: false

gaps:
  scale_with_dpi: true
  inner_gap: "24px"
  outer_gap:
    top: "0px"
    right: "24px"
    bottom: "24px"
    left: "24px"

window_effects:
  focused_window:
    border:
      enabled: true
      color: *ctp-mocha-mauve
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: true
      opacity: "95%"

  other_windows:
    border:
      enabled: true
      color: "#3c3c42"
    hide_title_bar:
      enabled: false
    corner_style:
      enabled: false
      style: "square"
    transparency:
      enabled: true
      opacity: "95%"

window_behavior:
  initial_state: "tiling"
  state_defaults:
    floating:
      centered: true
      shown_on_top: true
    fullscreen:
      maximized: false
      shown_on_top: false

workspaces:
  - name: "1"
  - name: "2"
  - name: "3"
  - name: "4"
  - name: "5"
  - name: "6"
  - name: "7"
  - name: "8"
  - name: "9"

window_rules:
  - commands: ["ignore"]
    match:
      - window_class: { regex: "TWizardForm|TApplication|#32770|OperationStatusWindow" }

  - commands: ["ignore"]
    match:
      - window_process: { equals: "msiexec" }

  - commands: ["ignore"]
    match:
      - window_title: { regex: "(?i).*setup.*|.*install.*|picture.in.picture|.*league.*" }

binding_modes:
  - name: "resize"
    keybindings:
      - commands: [ "resize --width +5%" ]
        bindings: [ "alt+left" ]
      - commands: [ "resize --width -5%" ]
        bindings: [ "alt+right" ]
      - commands: [ "resize --height -5%" ]
        bindings: [ "alt+up" ]
      - commands: [ "resize --height +5%" ]
        bindings: [ "alt+down" ]
      - commands: [ "wm-disable-binding-mode --name resize" ]
        bindings: [ "alt+shift+z" ]

  - name: "pause"
    keybindings:
      - commands: [ "wm-disable-binding-mode --name pause" ]
        bindings: [ "alt+shift+x" ]

keybindings:
  - commands: [ "focus --next-workspace" ]
    bindings: [ "alt+page_down" ]
  - commands: [ "focus --prev-workspace" ]
    bindings: [ "alt+page_up" ]
  - commands: [ "focus --recent-workspace" ]
    bindings: [ ]

  - commands: [ "focus --direction left" ]
    bindings: [ "alt+left" ]
  - commands: [ "focus --direction right" ]
    bindings: [ "alt+right" ]
  - commands: [ "focus --direction up" ]
    bindings: [ "alt+up" ]
  - commands: [ "focus --direction down" ]
    bindings: [ "alt+down" ]

  - commands: [ "move --direction left" ]
    bindings: [ "alt+shift+left" ]
  - commands: [ "move --direction right" ]
    bindings: [ "alt+shift+right" ]
  - commands: [ "move --direction up" ]
    bindings: [ "alt+shift+up" ]
  - commands: [ "move --direction down" ]
    bindings: [ "alt+shift+down" ]

  - commands: [ "focus --workspace 1" ]
    bindings: [ "control+1" ]
  - commands: [ "focus --workspace 2" ]
    bindings: [ "control+2" ]
  - commands: [ "focus --workspace 3" ]
    bindings: [ "control+3" ]
  - commands: [ "focus --workspace 4" ]
    bindings: [ "control+4" ]
  - commands: [ "focus --workspace 5" ]
    bindings: [ "control+5" ]
  - commands: [ "focus --workspace 6" ]
    bindings: [ "control+6" ]
  - commands: [ "focus --workspace 7" ]
    bindings: [ "control+7" ]
  - commands: [ "focus --workspace 8" ]
    bindings: [ "control+8" ]
  - commands: [ "focus --workspace 9" ]
    bindings: [ "control+9" ]

  - commands: [ "move --workspace 1", "focus --workspace 1" ]
    bindings: [ "control+shift+1" ]
  - commands: [ "move --workspace 2", "focus --workspace 2" ]
    bindings: [ "control+shift+2" ]
  - commands: [ "move --workspace 3", "focus --workspace 3" ]
    bindings: [ "control+shift+3" ]
  - commands: [ "move --workspace 4", "focus --workspace 4" ]
    bindings: [ "control+shift+4" ]
  - commands: [ "move --workspace 5", "focus --workspace 5" ]
    bindings: [ "control+shift+5" ]
  - commands: [ "move --workspace 6", "focus --workspace 6" ]
    bindings: [ "control+shift+6" ]
  - commands: [ "move --workspace 7", "focus --workspace 7" ]
    bindings: [ "control+shift+7" ]
  - commands: [ "move --workspace 8", "focus --workspace 8" ]
    bindings: [ "control+shift+8" ]
  - commands: [ "move --workspace 9", "focus --workspace 9" ]
    bindings: [ "control+shift+9" ]

  - commands: [ "move-workspace --direction left" ]
    bindings: [ ]
  - commands: [ "move-workspace --direction right" ]
    bindings: [ ]
  - commands: [ "move-workspace --direction up" ]
    bindings: [ ]
  - commands: [ "move-workspace --direction down" ]
    bindings: [ ]

  - commands: [ "wm-enable-binding-mode --name resize" ]
    bindings: [ "alt+shift+z" ]

  - commands: [ "wm-enable-binding-mode --name pause" ]
    bindings: [ "alt+shift+x" ]

  - commands: [ "wm-redraw" ]
    bindings: [ "alt+shift+c" ]

  - commands: [ "toggle-tiling-direction" ]
    bindings: [ "alt+shift+enter" ]

  - commands: [ "toggle-fullscreen" ]
    bindings: [ "alt+shift+insert" ]
  - commands: [ "toggle-floating" ]
    bindings: [ "alt+shift+home" ]
  - commands: [ "toggle-minimized" ]
    bindings: [ "alt+shift+delete" ]
  - commands: [ "close" ]
    bindings: [ "alt+shift+end" ]
  - commands: [ "toggle-tiling" ]
    bindings: [ ]

  - commands: [ "wm-cycle-focus" ]
    bindings: [ ]
  - commands: [ "wm-reload-config" ]
    bindings: [ ]
  - commands: [ "wm-exit" ]
    bindings: [ ]
